### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by MakerLab-Vector** [tobozo/ESP32-SIDView#3]
Hello! 
I want to build a SID player from this but getting a lot of compilation issues. I would be happy if you can help me pass the compilation process. I tried to use different ESP-IDF versions in Arduino IDE and followed all steps from closed issues. I was getting same errors but start getting different ones. I would be glad if you could share your code including libraries which compiles.

**Comment by VectorFever** [comment]
[log.txt](https://github.com/user-attachments/files/18550676/log.txt)

**Comment by MakerLab-Vector** [comment]
```log
> In file included from C:\Users\DIYMaker\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-442a798083/esp32/include/driver/deprecated/driver/i2s.h:23,
                 from C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src/SID6581.hpp:107,
                 from C:\Users\DIYMaker\Desktop\SIDPlay\ESP32-SIDView\src\config.h:119,
                 from C:\Users\DIYMaker\Desktop\SIDPlay\ESP32-SIDView\src\helpers\WiFiManager\WiFiManagerHooks.hpp:3,
                 from C:\Users\DIYMaker\Desktop\SIDPlay\ESP32-SIDView\src\helpers\WiFiManager\WiFiManagerHooks.cpp:1:
C:\Users\DIYMaker\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-442a798083/esp32/include/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
C:\Users\DIYMaker\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-442a798083/esp32/include/driver/deprecated/driver/i2s.h:27:2: warning: #warning "This set of I2S APIs has been deprecated, please include 'driver/i2s_std.h', 'driver/i2s_pdm.h' or 'driver/i2s_tdm.h' instead. if you want to keep using the old APIs and ignore this warning, you can enable 'Suppress leagcy driver deprecated warning' option under 'I2S Configuration' menu in Kconfig" [-Wcpp]
   27 | #warning "This set of I2S APIs has been deprecated, \
      |  ^~~~~~~
In file included from C:\Users\DIYMaker\Documents\Arduino\libraries\WiFiManagerTz\src/WiFiManagerTz.h:13,
                 from C:\Users\DIYMaker\Desktop\SIDPlay\ESP32-SIDView\src\helpers\WiFiManager\WiFiManagerHooks.cpp:4:
C:\Users\DIYMaker\Documents\Arduino\libraries\WiFiManager/strings_en.h:7:2: warning: #warning "This file is deprecated" [-Wcpp]
    7 | #warning "This file is deprecated"
      |  ^~~~~~~
In file included from C:\Users\DIYMaker\Documents\Arduino\libraries\gob_json-0.0.4\src/gob_json_handler.hpp:8,
                 from C:\Users\DIYMaker\Documents\Arduino\libraries\gob_json-0.0.4\src/gob_json.hpp:17,
                 from c:\users\diymaker\documents\arduino\libraries\sid6581-3.0.2-beta\src\modules\deepsid\deepsid.hpp:6,
                 from C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src/modules/Player/SID_Player.hpp:42,
                 from C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src/SID6581.hpp:931:
C:\Users\DIYMaker\Documents\Arduino\libraries\gob_json-0.0.4\src/gob_json_element_path.hpp:22:18: note: '#pragma message: [gob_json] Key length as default'
   22 | # pragma message "[gob_json] Key length as default"
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\gob_json-0.0.4\src/gob_json_element_path.hpp:30:18: note: '#pragma message: [gob_json] Stack max depth as default'
   30 | # pragma message "[gob_json] Stack max depth as default"
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\gob_json-0.0.4\src/gob_json.hpp:40:18: note: '#pragma message: [gob_json] Buffer length as default'
   40 | # pragma message "[gob_json] Buffer length as default"
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:\Users\DIYMaker\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-442a798083/esp32/include/driver/deprecated/driver/i2s.h:23,
                 from C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src/SID6581.hpp:107,
                 from C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\MOS\MOS_CPU_Controls.hpp:34,
                 from C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\MOS\MOS_CPU_Controls.cpp:31:
C:\Users\DIYMaker\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-442a798083/esp32/include/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
C:\Users\DIYMaker\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-442a798083/esp32/include/driver/deprecated/driver/i2s.h:27:2: warning: #warning "This set of I2S APIs has been deprecated, please include 'driver/i2s_std.h', 'driver/i2s_pdm.h' or 'driver/i2s_tdm.h' instead. if you want to keep using the old APIs and ignore this warning, you can enable 'Suppress leagcy driver deprecated warning' option under 'I2S Configuration' menu in Kconfig" [-Wcpp]
   27 | #warning "This set of I2S APIs has been deprecated, \
      |  ^~~~~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\MOS\MOS_CPU_Controls.cpp: In member function 'void MOS_CPU_Controls::feedTheDog()':
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\MOS\MOS_CPU_Controls.cpp:45:40: error: 'timg_dev_t' {aka 'struct timg_dev_t'} has no member named 'wdt_wprotect'; did you mean 'wdtwprotect'?
   45 |   #define TIMERG0_wdt_wprotect TIMERG0.wdt_wprotect
      |                                        ^~~~~~~~~~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\MOS\MOS_CPU_Controls.cpp:58:3: note: in expansion of macro 'TIMERG0_wdt_wprotect'
   58 |   TIMERG0_wdt_wprotect=TIMER_WRITE_ENABLE; // write enable
      |   ^~~~~~~~~~~~~~~~~~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\MOS\MOS_CPU_Controls.cpp:47:40: error: 'timg_dev_t' {aka 'struct timg_dev_t'} has no member named 'wdt_feed'; did you mean 'wdtfeed'?
   47 |   #define TIMERG0_wdt_feed     TIMERG0.wdt_feed
      |                                        ^~~~~~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\MOS\MOS_CPU_Controls.cpp:59:3: note: in expansion of macro 'TIMERG0_wdt_feed'
   59 |   TIMERG0_wdt_feed=1;                       // feed dog
      |   ^~~~~~~~~~~~~~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\MOS\MOS_CPU_Controls.cpp:45:40: error: 'timg_dev_t' {aka 'struct timg_dev_t'} has no member named 'wdt_wprotect'; did you mean 'wdtwprotect'?
   45 |   #define TIMERG0_wdt_wprotect TIMERG0.wdt_wprotect
      |                                        ^~~~~~~~~~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\MOS\MOS_CPU_Controls.cpp:60:3: note: in expansion of macro 'TIMERG0_wdt_wprotect'
   60 |   TIMERG0_wdt_wprotect=0;                   // write protect
      |   ^~~~~~~~~~~~~~~~~~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\MOS\MOS_CPU_Controls.cpp:46:40: error: 'timg_dev_t' {aka 'struct timg_dev_t'} has no member named 'wdt_wprotect'; did you mean 'wdtwprotect'?
   46 |   #define TIMERG1_wdt_wprotect TIMERG1.wdt_wprotect
      |                                        ^~~~~~~~~~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\MOS\MOS_CPU_Controls.cpp:62:3: note: in expansion of macro 'TIMERG1_wdt_wprotect'
   62 |   TIMERG1_wdt_wprotect=TIMER_WRITE_ENABLE; // write enable
      |   ^~~~~~~~~~~~~~~~~~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\MOS\MOS_CPU_Controls.cpp:48:40: error: 'timg_dev_t' {aka 'struct timg_dev_t'} has no member named 'wdt_feed'; did you mean 'wdtfeed'?
   48 |   #define TIMERG1_wdt_feed     TIMERG0.wdt_feed
      |                                        ^~~~~~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\MOS\MOS_CPU_Controls.cpp:63:3: note: in expansion of macro 'TIMERG1_wdt_feed'
   63 |   TIMERG1_wdt_feed=1;                       // feed dog
      |   ^~~~~~~~~~~~~~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\MOS\MOS_CPU_Controls.cpp:46:40: error: 'timg_dev_t' {aka 'struct timg_dev_t'} has no member named 'wdt_wprotect'; did you mean 'wdtwprotect'?
   46 |   #define TIMERG1_wdt_wprotect TIMERG1.wdt_wprotect
      |                                        ^~~~~~~~~~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\MOS\MOS_CPU_Controls.cpp:64:3: note: in expansion of macro 'TIMERG1_wdt_wprotect'
   64 |   TIMERG1_wdt_wprotect=0;                   // write protect
      |   ^~~~~~~~~~~~~~~~~~~~
In file included from C:\Users\DIYMaker\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-442a798083/esp32/include/driver/deprecated/driver/i2s.h:23,
                 from C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\SID6581.hpp:107,
                 from C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\SID6581.cpp:31:
C:\Users\DIYMaker\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-442a798083/esp32/include/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
C:\Users\DIYMaker\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-442a798083/esp32/include/driver/deprecated/driver/i2s.h:27:2: warning: #warning "This set of I2S APIs has been deprecated, please include 'driver/i2s_std.h', 'driver/i2s_pdm.h' or 'driver/i2s_tdm.h' instead. if you want to keep using the old APIs and ignore this warning, you can enable 'Suppress leagcy driver deprecated warning' option under 'I2S Configuration' menu in Kconfig" [-Wcpp]
   27 | #warning "This set of I2S APIs has been deprecated, \
      |  ^~~~~~~
In file included from C:\Users\DIYMaker\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-442a798083/esp32/include/driver/deprecated/driver/i2s.h:23,
                 from C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src/SID6581.hpp:107,
                 from c:\users\diymaker\documents\arduino\libraries\sid6581-3.0.2-beta\src\modules\player\sid_track.h:34,
                 from C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\HVSC\SID_HVSC_Indexer.hpp:47,
                 from C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\HVSC\SID_HVSC_Indexer.cpp:41:
C:\Users\DIYMaker\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-442a798083/esp32/include/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
C:\Users\DIYMaker\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-442a798083/esp32/include/driver/deprecated/driver/i2s.h:27:2: warning: #warning "This set of I2S APIs has been deprecated, please include 'driver/i2s_std.h', 'driver/i2s_pdm.h' or 'driver/i2s_tdm.h' instead. if you want to keep using the old APIs and ignore this warning, you can enable 'Suppress leagcy driver deprecated warning' option under 'I2S Configuration' menu in Kconfig" [-Wcpp]
   27 | #warning "This set of I2S APIs has been deprecated, \
      |  ^~~~~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\HVSC\SID_HVSC_Indexer.cpp: In member function 'bool BufferedIndex::open(const char*, bool)':
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\HVSC\SID_HVSC_Indexer.cpp:80:16: warning: array subscript 'fileIndex_t[0]' is partly outside array bounds of 'unsigned char [5]' [-Warray-bounds]
   80 |     IndexItem->path = (char*)sid_calloc( 1, 256 );
      |     ~~~~~~~~~~~^~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\HVSC\SID_HVSC_Indexer.cpp:75:41: note: object of size 5 allocated by 'calloc'
   75 |     IndexItem = (fileIndex_t*)sid_calloc( 1, sizeof( IndexItem )+1 );
In file included from C:\Users\DIYMaker\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-442a798083/esp32/include/driver/deprecated/driver/i2s.h:23,
                 from C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src/SID6581.hpp:107,
                 from c:\users\diymaker\documents\arduino\libraries\sid6581-3.0.2-beta\src\modules\player\sid_track.h:34,
                 from C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\Deepsid\Deepsid.hpp:8,
                 from C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\Deepsid\Deepsid.cpp:2:
C:\Users\DIYMaker\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-442a798083/esp32/include/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
C:\Users\DIYMaker\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-442a798083/esp32/include/driver/deprecated/driver/i2s.h:27:2: warning: #warning "This set of I2S APIs has been deprecated, please include 'driver/i2s_std.h', 'driver/i2s_pdm.h' or 'driver/i2s_tdm.h' instead. if you want to keep using the old APIs and ignore this warning, you can enable 'Suppress leagcy driver deprecated warning' option under 'I2S Configuration' menu in Kconfig" [-Wcpp]
   27 | #warning "This set of I2S APIs has been deprecated, \
      |  ^~~~~~~
In file included from C:\Users\DIYMaker\Documents\Arduino\libraries\gob_json-0.0.4\src/gob_json_handler.hpp:8,
                 from C:\Users\DIYMaker\Documents\Arduino\libraries\gob_json-0.0.4\src/gob_json.hpp:17,
                 from C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\Deepsid\Deepsid.hpp:6:
C:\Users\DIYMaker\Documents\Arduino\libraries\gob_json-0.0.4\src/gob_json_element_path.hpp:22:18: note: '#pragma message: [gob_json] Key length as default'
   22 | # pragma message "[gob_json] Key length as default"
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\gob_json-0.0.4\src/gob_json_element_path.hpp:30:18: note: '#pragma message: [gob_json] Stack max depth as default'
   30 | # pragma message "[gob_json] Stack max depth as default"
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\gob_json-0.0.4\src/gob_json.hpp:40:18: note: '#pragma message: [gob_json] Buffer length as default'
   40 | # pragma message "[gob_json] Buffer length as default"
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\Deepsid\Deepsid.cpp: In function 'void net::wifiOn()':
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\Deepsid\Deepsid.cpp:464:14: error: 'WiFi' was not declared in this scope
  464 |       while (WiFi.status() != WL_CONNECTED && wifi_retry_count < max_retries)
      |              ^~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\Deepsid\Deepsid.cpp:464:31: error: 'WL_CONNECTED' was not declared in this scope
  464 |       while (WiFi.status() != WL_CONNECTED && wifi_retry_count < max_retries)
      |                               ^~~~~~~~~~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\Deepsid\Deepsid.cpp:485:9: error: 'WiFi' was not declared in this scope
  485 |     if (WiFi.waitForConnectResult() == WL_CONNECTED){
      |         ^~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\Deepsid\Deepsid.cpp:485:40: error: 'WL_CONNECTED' was not declared in this scope
  485 |     if (WiFi.waitForConnectResult() == WL_CONNECTED){
      |                                        ^~~~~~~~~~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\Deepsid\Deepsid.cpp: In function 'void net::wifiOff()':
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\Deepsid\Deepsid.cpp:495:9: error: 'WiFi' was not declared in this scope
  495 |     if( WiFi.getMode() != WIFI_OFF ) {
      |         ^~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\Deepsid\Deepsid.cpp:495:27: error: 'WIFI_OFF' was not declared in this scope
  495 |     if( WiFi.getMode() != WIFI_OFF ) {
      |                           ^~~~~~~~
In file included from C:\Users\DIYMaker\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-442a798083/esp32/include/driver/deprecated/driver/i2s.h:23,
                 from C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src/SID6581.hpp:107,
                 from C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\Player\SID_Player.hpp:35,
                 from C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\Player\SID_Player.cpp:31:
C:\Users\DIYMaker\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-442a798083/esp32/include/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
C:\Users\DIYMaker\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-442a798083/esp32/include/driver/deprecated/driver/i2s.h:27:2: warning: #warning "This set of I2S APIs has been deprecated, please include 'driver/i2s_std.h', 'driver/i2s_pdm.h' or 'driver/i2s_tdm.h' instead. if you want to keep using the old APIs and ignore this warning, you can enable 'Suppress leagcy driver deprecated warning' option under 'I2S Configuration' menu in Kconfig" [-Wcpp]
   27 | #warning "This set of I2S APIs has been deprecated, \
      |  ^~~~~~~
In file included from C:\Users\DIYMaker\Documents\Arduino\libraries\gob_json-0.0.4\src/gob_json_handler.hpp:8,
                 from C:\Users\DIYMaker\Documents\Arduino\libraries\gob_json-0.0.4\src/gob_json.hpp:17,
                 from c:\users\diymaker\documents\arduino\libraries\sid6581-3.0.2-beta\src\modules\deepsid\deepsid.hpp:6,
                 from C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\Player\SID_Player.hpp:42:
C:\Users\DIYMaker\Documents\Arduino\libraries\gob_json-0.0.4\src/gob_json_element_path.hpp:22:18: note: '#pragma message: [gob_json] Key length as default'
   22 | # pragma message "[gob_json] Key length as default"
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\gob_json-0.0.4\src/gob_json_element_path.hpp:30:18: note: '#pragma message: [gob_json] Stack max depth as default'
   30 | # pragma message "[gob_json] Stack max depth as default"
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\gob_json-0.0.4\src/gob_json.hpp:40:18: note: '#pragma message: [gob_json] Buffer length as default'
   40 | # pragma message "[gob_json] Buffer length as default"
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\Player\SID_Player.cpp: In function 'const char* hexString32(uint32_t, char*)':
C:\Users\DIYMaker\Documents\Arduino\libraries\SID6581-3.0.2-beta\src\modules\Player\SID_Player.cpp:731:26: warning: format '%x' expects argument of type 'unsigned int', but argument 4 has type 'uint32_t' {aka 'long unsigned int'} [-Wformat=]
  731 |   snprintf(buf, 10, "$%08x", hexval );
      |                       ~~~^   ~~~~~~
      |                          |   |
      |                          |   uint32_t {aka long unsigned int}
      |                          unsigned int
      |                       %08lx
exit status 1
Compilation error: exit status 1
```
That's what I got...

**Comment by tobozo** [comment]
Hi,

Given the last push on this repo is 2 years old, the best match arduino core version would be [2.0.14](https://github.com/espressif/arduino-esp32/releases/tag/2.0.14) and should work with the master branch of [SID6581](https://github.com/hpwit/SID6581) library.

If it doens't give satisfying results, the SID6581 library has an [experimental branch](https://github.com/hpwit/SID6581/tree/3.0.2-beta) that should work with [arduino-esp32 3.0.2](https://github.com/espressif/arduino-esp32/releases/tag/3.0.2) (based on esp-idf 5.1.4).
